spring.application.name=profanity-service
server.port=8200
eureka.client.service-url.default-zone=http://localhost:8761/eureka

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=profanity_db
